name: Ember

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Copy .env
        run: cp .env.example .env
      - name: JavaScript Linting
        run: npm run lint:js
      - name: Template Linting
        run: npm run lint:hbs
      - name: Test App
        run: npm run test:ember
        env:
          CI: true
